services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: OsQh7z9tXqV/W5ko5ximKH+ntX2keQ9iJhr4W9pZF0E=
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        value: https://n8n-on-render-palc.onrender.com/
